# Generated by Django 2.2.6 on 2020-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_clone', '0002_remove_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
