# Generated by Django 2.2.6 on 2020-03-01 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora_clone', '0005_auto_20200229_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='QuesAns',
        ),
    ]
